### ISSUE TITLE
Empty report in case of reusable enum

### ISSUE THREAD

**Issue by Scofield62** [Surnet/swagger-jsdoc#232] opened 2020-12-07 13:57 UTC
app.js:
``` javascript
const swaggerDefinition = {
  info: {
    title: ' API',
    version: 'v1',
  },
  host: address,
};

const swaggerOptions = {
  swaggerDefinition: {
    components: {}
  },
  apis: ['./controllers/api.js']
};
```
Endpoints with definitions:
``` javascript
/**
  * @swagger
  * definitions:
  *   Types:
  *     type: string
  *     schema:
  *       enum: &TAXTYPES [one, two]
  * components:
  *   parameters:
  *     type:
  *       name: type
  *       in: path
  *       enum: *TAXTYPES
  *       required: true
*/


/** 
  * @swagger
  * /api/{type}/v1:
  *   get:
  *     tags: [default]
  *     parameters:
  *       - $ref: '#/components/parameters/type'
  *     description: Example of types
*/
router.get('/v1', async (req, res) => {...
```

I got the following message in the console when I ran app.js:

```
Not all input has been taken into account at your final specification.
Here's the report: 



```

Once I take out the enum: *TAXTYPES the message doesn't appear. I assume the problem is with this character: *, but unfortunately this is how we can define reusable enumerators.

I kindly ask someone to investigate it. Thanks in advance!

**Comment by kalinchernev** [comment] 2020-12-07 14:56
You're right the issue will most probably be related to the yaml anchors/aliases of `TAXTYPES`

The subject got started in https://github.com/Surnet/swagger-jsdoc/issues/152 and I've been trying to handle in v6 which is in release candidate cycle for the exact reason I'm not fully confident on this feature of yaml copy paste just yet.

Can you try rewriting this part in a similar way as this https://github.com/Surnet/swagger-jsdoc/tree/master/example/yaml-anchors-aliases? I'm not expert in how this yaml feature works, but followed the example of the issue. Please share your findings as your issue could appear to be a very good test case for this particular issue. 

That's the reason I've kept https://github.com/Surnet/swagger-jsdoc/blob/master/example/yaml-anchors-aliases/yaml-anchors-aliases.spec.js as a separate test suite in order to enable easier setup/development of this particular feature

Feel free to clone the repo, put your example there, reproduce, try to see whether it's something in the yaml syntax and eemeli/yaml parser expecting different yaml syntax. It could be that the error reported by the parser hasn't been handled well https://github.com/Surnet/swagger-jsdoc/blob/master/src/specification.js#L207

**Comment by Scofield62** [comment] 2020-12-08 18:21
Sure. Once I have some time look at it more deeply. Thanks for the quick reply. :)

**Comment by Scofield62** [comment] 2020-12-14 17:02
I could solve the issue with changing version from 2.0 to 3.0. (This anchor is not supported in 3.0 as I know, but the enum usage improved).

I will try to recreate it with version 2.

**Comment by kalinchernev** [comment] 2020-12-15 15:46
Oh yes, you're right, `components` is part of v3 https://stoplight.io/blog/difference-between-open-v2-v3-v31/#specification-restructured-to-increase-reusability

Seems like the issue could be related to swagger parser rather than yaml anchors.

Please keep me updated if you manage to reproduce in v2

**Comment by Scofield62** [comment] 2020-12-15 16:07
I just found this:

https://stackoverflow.com/questions/32255384/swagger-reusing-an-enum-definition-as-query-parameter

It says it is impossible. There is no solution to get it work in swagger 2. So I would just close this ticket.

**Comment by kalinchernev** [comment] 2020-12-16 06:00
Thank you @Scofield62 for following up. I'm closing for now

**Closed by kalinchernev** 2020-12-16 06:00 UTC
