### ISSUE TITLE
Generating swagger docs from typescript interfaces

### ISSUE THREAD

**Issue by adrian-moisa** [Surnet/swagger-jsdoc#148] opened 2018-12-01 11:57 UTC
Hi there,

I was wondering is there any way to generate the swager docs automatically from typescript interfaces.
I have a lot of them in the project and also a lot of mongoose schemas and models. It is getting tedious to keep them in sync. On the other hand I do not want to use the swagger generation tools. I preffer the bottom-up approach.

Cheers

**Comment by adrian-moisa** [comment] 2018-12-01 14:09
Found [typegoose](https://github.com/szokodiakos/typegoose). That solves half the problem :D Still searching for the swagger counterpart.

**Comment by kalinchernev** [comment] 2018-12-02 13:44
Hi @adrian-moisa, I don't have any experience with typescript. There is, however, a [closed issue which gets bumped from time to time](https://github.com/Surnet/swagger-jsdoc/issues/62) with similar questions.

If you have any suggestions, I'm open to accept pull requests for better integrations with typescript. My only request is to have steps to reproduce and test for people without experience with typescript :P

**Comment by nelsou** [comment] 2019-01-10 10:32
Any update on this one ?

**Comment by manwaring** [comment] 2020-05-03 00:44
@adrian-moisa A year and a half later and I'm searching for the same thing you were - did you ever find a library you liked that supports TypeScript -> Swagger/OpenAPI generation?

**Comment by francescov1** [comment] 2020-10-13 17:18
I was looking for something to accomplish this and just came across [tsoa](https://github.com/lukeautry/tsoa), looks pretty promising!

**Comment by kalinchernev** [comment] 2020-10-14 06:05
Hi @francescov1 and thanks for the sharing. I'll leave the issue open for further discussions, however I don't see how typescript-related tools will be beneficial in this project. From my understanding of jsdoc and ts at the moment, and reading [this article](https://medium.com/javascript-scene/the-typescript-tax-132ff4cb175b) some time ago, it seems to me one should pick one or the other: either jsdoc comments or ts annotations.

> API Documentation: Another great benefit of TypeScript is better documentation for APIs which is always in sync with your source code. You can even generate API documentation from your TypeScript code. This would also get a higher score, except you can get the same benefit using JSDoc and Tern.js in JavaScript, and documentation generators are abundant. Personally, I’m not a big fan of JSDoc, so TypeScript does get some points, here.

**Comment by kalinchernev** [comment] 2020-11-25 16:21
Closing the issue because https://github.com/Surnet/swagger-jsdoc/issues/148#issuecomment-707890509 seems like a nice suggestion

**Closed by kalinchernev** 2020-11-25 16:21 UTC

**Comment by crossan007** [comment] 2022-01-21 19:00
Came here to open this issue; am glad there's already a decent solution!

**Comment by pchodak** [comment] 2023-09-19 12:34
Does anyone have a solution to handle in swagger DTO/interface like in java
